using System;
using Enums;
using Signals;
using UnityEngine;

namespace Controllers
{
    public class IdleStartPhysicsController : MonoBehaviour
    {
        #region Self Variables
        #region Serialized Variables

        [SerializeField] private GameObject 覺dleObj;

        #endregion
        #region Private Variables

        #endregion
        #endregion
        private void OnTriggerExit(Collider other)
        {
            if (other.CompareTag("Player"))
            {
                覺dleObj.transform.position = other.transform.position;
                覺dleObj.SetActive(true);
                PlayerSignals.Instance.onPlayCamera?.Invoke(CameraState.Casual);
                MinigameSignals.Instance.onSetCamera?.Invoke(覺dleObj);
                CoreGameSignals.Instance.onGameChange?.Invoke();
                
                //transform.GetComponent<BoxCollider>().isTrigger = false;
            }
        }
    }
}